apiVersion: v1
kind: Service
metadata:
  name: sa-hadoop-base
spec:
  type: LoadBalancer
  loadBalancerIP: 35.227.16.143
  ports:
    - port: 9870
      protocol: TCP
      targetPort: 50070

  selector:
    app: sa-hadoop-base