apiVersion: v1
kind: Service
metadata:
  name: sa-jupyter
spec:
  type: LoadBalancer
  loadBalancerIP: 35.227.16.143
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: sa-jupyter